config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :posts,   only: [:show, :edit, :destroy, :create, :update] do
    resources :comments, only:[:create]
  end
  resources :comments, only: [:destroy]
  resources :versions,only: [:edit, :update ]
  resources :attachments, only: [:index, :create]

  devise_for :users, controllers: { registrations: "users/registrations" }

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, inverse_of: :post

  after_create do
    # Ensure versions after_save
    self.ensure_versions
    true
  end

  has_many :versions, inverse_of: :post

  def ensure_versions
    # Check no-exists versions and create them
    I18n.available_locales.each do |lang|
      self.versions.find_or_create_by(lang: lang) do |ver|
        ver.title   = ""
        ver.content = ""
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def show
    @versions = @post.versions
    @version = @versions.find_by(lang: I18n.locale)
    @comments = @post.comments.order("id DESC").paginate(page: params[:comments_page])
    if @version.present?
    else
      redirect_to :back
    end
  end

  def edit
    @versions = @post.versions
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to edit_post_path(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    redirect_to "/"
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.fetch(:post, {}).permit(:is_published, :rank)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">

        <div class="panel-body">
          <%= link_to t('back'), @post %>
          <span class="pull-right"><%= link_to t('delete'), post_path(@post), class: 'text-danger', data: { method: :delete, confirm: t(:confirm_delete_post) } %></span>

          <h4 class="text-center"><%= t(:edit_post) %> #<%= @post.id %>
          </h4>
        </div>

        <div class="list-group">
          <% @versions.each do |ver| %>
          <%= link_to "#{I18n.locale_name(ver.lang)}: #{ver.title}", edit_version_path(ver), class: 'list-group-item' %>
          <% end %>
        </div>

        <div class="panel-body">

          <%= form_for(@post) do |f| %>
          <div class="form-group">
            <label>Rank</label>
            <%= f.text_field :rank, class: 'form-control' %>
          </div>
          <div class="checkbox">
            <label>
              <%= f.check_box :is_published %> <%= t(:publish) %>
            </label>
          </div>
          <div class="form-group text-center">
            <%= f.submit t(:confirm), class: 'btn btn-primary' %>
          </div>
          <% end %>

        </div>


      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :page_title, @version.title + " |" %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2><%= @version.title %></h2>
      <h5 class="text-muted"><%= time_ago_in_words @version.created_at %></h5>
      <% if user_signed_in? %>
      <h6 class="text-right"><%= link_to 'Edit', edit_post_path(@post) %></h6>
      <% end %>
      <hr/>
      <%= @version.content_rich.html_safe %>
      <hr/>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading"><%= t(:comments) %></div>
        <% if will_paginate(@comments).present? %>
        <div class="panel-body text-center">
          <%= will_paginate @comments, class: 'pagination' %>
        </div>
        <% end %>
        <ul class="list-group">
          <% if @comments.empty? %>
          <li class="list-group-item text-muted text-center">
            <%= t(:no_comments) %>
          </li>
          <% else %>
          <% @comments.each do |comment| %>
          <li class="list-group-item">
            <h5><%= comment.nickname %>
              <% if comment.is_admin %>
              <span class="glyphicon glyphicon-star text-warning" aria-hidden="true"></span>
              <% end %>
              &nbsp;
              <span class="text-muted pull-right"><%= time_ago_in_words comment.created_at %></span>
              <% if user_signed_in? %>
              <%= link_to t(:delete), comment_path(comment), method: :delete, data:{ confirm: t(:confirm_delete_comment) } %>
              <% end %>
            </h5>
            <%= comment.content %>
          </li>
          <% end %>
          <% end %>
        </ul>
        <% if will_paginate(@comments).present? %>
        <div class="panel-body text-center">
          <%= will_paginate @comments, class: 'pagination' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><%= t(:create_comment) %></div>
        <div class="panel-body">
          <%= form_for Comment.new(nickname: cookies.permanent[:nickname]), url: post_comments_path(@post) do |f| %>
          <div class="form-group">
            <label><%= t(:nickname) %></label>
            <%= f.text_field :nickname, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label><%= t(:content) %></label>
            <%= f.text_area :content, class: 'form-control' %>
          </div>
          <div class="form-group text-right">
            <%= f.submit t(:submit), class: 'btn btn-primary' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>