config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :posts,   only: [:show, :edit, :destroy, :create, :update] do
    resources :comments, only:[:create]
  end
  resources :comments, only: [:destroy]
  resources :versions,only: [:edit, :update ]
  resources :attachments, only: [:index, :create]

  devise_for :users, controllers: { registrations: "users/registrations" }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :page_title %> YANKE.IO</title>
  <meta name="viewport" content="width=device-width,user-scalable=no" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- GA Head -->
  <%= render 'shared/ga_head' %>
</head>
<body>
  <!-- title -->

  <div class="title-box text-primary">
    <%= link_to "/" do %>
    <h3>YANKE.IO</h3>
    <% end %>
  </div>

  <!-- navbar -->
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <span class="navbar-brand">
          <%= image_tag "avatar.png" %>
        </span>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">YANKE Guo</a></li>
          <li><a href="mailto:hi@yanke.io"><i class="fa fa-envelope-o fa-lg"></i></a></li>
          <li><a href="https://twitter.com/yanke_guo"><i class="fa fa-twitter fa-lg"></i></a></li>
          <li><a href="https://github.com/yanke-guo"><i class="fa fa-github fa-lg"></i></a></li>
          <li><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KTR8BN7CF9CZ4"><i class="fa fa-usd fa-lg"></i></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% I18n.available_locales.each do |lang| %>
          <%= i18n_li_link lang %>
          <% end %>
        </ul>
        <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t(:logout), destroy_user_session_path, method: :delete %></li>
          <li><%= link_to t(:new_post), posts_path, method: :post %></li>
          <li><%= link_to t(:attachments), attachments_path %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </div>

  <%= yield %>

  <!-- Footer -->
  <%= render 'shared/footer' %>

  <!-- GA Page View -->
  <%= render 'shared/ga_page_view' %>

</body>
</html>